-- direct emulation of the CSV file
-- DROP VIEW IF EXISTS my_report; CREATE VIEW my_report AS
SELECT
    matches.id,
    events.atp AS "ATP",
    locations.name AS "Location",
    tournaments.name AS "Tournament",
    matches.date AS "Date",
    events.series AS "Series",
    courts.court AS "Court",
    courts.surface AS "Surface",
    matches.round AS "Round",
    matches.best_of AS "Best of",
    winner_player.name AS "Winner",
    loser_player.name AS "Loser",
    winner_player_m.new_rank AS "WRank",
    loser_player_m.new_rank AS "LRank",
    winner_player_m.new_points AS "WPts",
    loser_player_m.new_points AS "LPts",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=winner_player_m.id AND set_num=1) AS "W1",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=loser_player_m.id AND set_num=1) AS "L1",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=winner_player_m.id AND set_num=2) AS "W2",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=loser_player_m.id AND set_num=2) AS "L2",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=winner_player_m.id AND set_num=3) AS "W3",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=loser_player_m.id AND set_num=3) AS "L3",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=winner_player_m.id AND set_num=4) AS "W4",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=loser_player_m.id AND set_num=4) AS "L4",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=winner_player_m.id AND set_num=5) AS "W5",
    (SELECT games FROM players_matches_sets WHERE players_matches_id=loser_player_m.id AND set_num=5) AS "L5",
    matches.comment AS "Comment",
    winner_player.flag AS "pl1_flag",
    winner_player.year_pro AS "pl1_year_pro",
    winner_player.weight AS "pl1_weight",
    winner_player.height AS "pl1_height",
    winner_player.hand AS "pl1_hand",
    loser_player.flag AS "pl2_flag",
    loser_player.year_pro AS "pl2_year_pro",
    loser_player.weight AS "pl2_weight",
    loser_player.height AS "pl2_height",
    loser_player.hand AS "pl2_hand"
FROM matches
JOIN events ON matches.event_id=events.id
JOIN tournaments ON events.tournament_id=tournaments.id
JOIN locations ON events.location_id=locations.id
JOIN courts ON matches.court_id=courts.id
JOIN players_matches AS winner_player_m ON winner_player_m.match_id=matches.id AND winner_player_m.win=TRUE
JOIN players AS winner_player ON winner_player.id=winner_player_m.player_id
JOIN players_matches AS loser_player_m ON loser_player_m.match_id=matches.id AND loser_player_m.win=FALSE
JOIN players AS loser_player ON loser_player.id=loser_player_m.player_id
ORDER BY matches.id;

SELECT * FROM (
SELECT *, (ATP+Location+Tournament+Date+Series+Court+Surface+Round+"Best of"+Winner+Loser+WRank+LRank+WPts+LPts+W1+L1+W2+L2+W3+L3+W4+L4+W5+L5+pl1_flag+pl1_year_pro+pl1_weight+pl1_height+pl1_hand+pl2_flag+pl2_year_pro+pl2_weight+pl2_height+pl2_hand) AS bad
FROM (
SELECT
    r.id,
    r."ATP" AS "ATP(r)",
    t."ATP" AS "ATP(t)",
    r."ATP"<>CAST(t."ATP" AS TEXT) AS "ATP",
    r."Location" AS "Location(r)",
    t."Location" AS "Location(t)",
    r."Location"<>t."Location" AS "Location",
    r."Tournament" AS "Tournament(r)",
    t."Tournament" AS "Tournament(t)",
    r."Tournament"<>t."Tournament" AS "Tournament",
    r."Date" AS "Date(r)",
    t."Date" AS "Date(t)",
    r."Date"<>strftime('%d/%m/%Y', t."Date") AS "Date",
    r."Series" AS "Series(r)",
    t."Series" AS "Series(t)",
    r."Series"<>t."Series" AS "Series",
    r."Court" AS "Court(r)",
    t."Court" AS "Court(t)",
    r."Court"<>t."Court" AS "Court",
    r."Surface" AS "Surface(r)",
    t."Surface" AS "Surface(t)",
    r."Surface"<>t."Surface" AS "Surface",
    r."Round" AS "Round(r)",
    t."Round" AS "Round(t)",
    r."Round"<>t."Round" AS "Round",
    r."Best of" AS "Best of(r)",
    t."Best of" AS "Best of(t)",
    r."Best of"<>CAST(t."Best of" AS TEXT) AS "Best of",
    r."Winner" AS "Winner(r)",
    t."Winner" AS "Winner(t)",
    r."Winner"<>t."Winner" AS "Winner",
    r."Loser" AS "Loser(r)",
    t."Loser" AS "Loser(t)",
    r."Loser"<>t."Loser" AS "Loser",
    r."WRank" AS "WRank(r)",
    t."WRank" AS "WRank(t)",
    r."WRank"<>CAST(coalesce(t."WRank", '') AS TEXT) AS "WRank",
    r."LRank" AS "LRank(r)",
    t."LRank" AS "LRank(t)",
    r."LRank"<>CAST(coalesce(t."LRank", '') AS TEXT) AS "LRank",
    r."WPts" AS "WPts(r)",
    t."WPts" AS "WPts(t)",
    r."WPts"<>CAST(coalesce(t."WPts", '') AS TEXT) AS "WPts",
    r."LPts" AS "LPts(r)",
    t."LPts" AS "LPts(t)",
    r."LPts"<>CAST(coalesce(t."LPts", '') AS TEXT) AS "LPts",
    r."W1" AS "W1(r)",
    t."W1" AS "W1(t)",
    r."W1"<>CAST(coalesce(t."W1", '') AS TEXT) AS "W1",
    r."L1" AS "L1(r)",
    t."L1" AS "L1(t)",
    r."L1"<>CAST(coalesce(t."L1", '') AS TEXT) AS "L1",
    r."W2" AS "W2(r)",
    t."W2" AS "W2(t)",
    r."W2"<>CAST(coalesce(t."W2", '') AS TEXT) AS "W2",
    r."L2" AS "L2(r)",
    t."L2" AS "L2(t)",
    r."L2"<>CAST(coalesce(t."L2", '') AS TEXT) AS "L2",
    r."W3" AS "W3(r)",
    t."W3" AS "W3(t)",
    r."W3"<>CAST(coalesce(t."W3", '') AS TEXT) AS "W3",
    r."L3" AS "L3(r)",
    t."L3" AS "L3(t)",
    r."L3"<>CAST(coalesce(t."L3", '') AS TEXT) AS "L3",
    r."W4" AS "W4(r)",
    t."W4" AS "W4(t)",
    r."W4"<>CAST(coalesce(t."W4", '') AS TEXT) AS "W4",
    r."L4" AS "L4(r)",
    t."L4" AS "L4(t)",
    r."L4"<>CAST(coalesce(t."L4", '') AS TEXT) AS "L4",
    r."W5" AS "W5(r)",
    t."W5" AS "W5(t)",
    r."W5"<>CAST(coalesce(t."W5", '') AS TEXT) AS "W5",
    r."L5" AS "L5(r)",
    t."L5" AS "L5(t)",
    r."L5"<>CAST(coalesce(t."L5", '') AS TEXT) AS "L5",
    r."Comment" AS "Comment(r)",
    t."Comment" AS "Comment(t)",
    r."Comment"<>t."Comment" AS "Comment",
    r."pl1_flag" AS "pl1_flag(r)",
    t."pl1_flag" AS "pl1_flag(t)",
    r."pl1_flag"<>coalesce(t."pl1_flag", '') AS "pl1_flag",
    r."pl1_year_pro" AS "pl1_year_pro(r)",
    t."pl1_year_pro" AS "pl1_year_pro(t)",
    r."pl1_year_pro"<>CAST(coalesce(t."pl1_year_pro", '') AS TEXT) AS "pl1_year_pro",
    r."pl1_weight" AS "pl1_weight(r)",
    t."pl1_weight" AS "pl1_weight(t)",
    r."pl1_weight"<>CAST(coalesce(t."pl1_weight", '') AS TEXT) AS "pl1_weight",
    r."pl1_height" AS "pl1_height(r)",
    t."pl1_height" AS "pl1_height(t)",
    r."pl1_height"<>CAST(coalesce(t."pl1_height", '') AS TEXT) AS "pl1_height",
    r."pl1_hand" AS "pl1_hand(r)",
    t."pl1_hand" AS "pl1_hand(t)",
    r."pl1_hand"<>coalesce(t."pl1_hand", '') AS "pl1_hand",
    r."pl2_flag" AS "pl2_flag(r)",
    t."pl2_flag" AS "pl2_flag(t)",
    r."pl2_flag"<>coalesce(t."pl2_flag", '') AS "pl2_flag",
    r."pl2_year_pro" AS "pl2_year_pro(r)",
    t."pl2_year_pro" AS "pl2_year_pro(t)",
    r."pl2_year_pro"<>CAST(coalesce(t."pl2_year_pro", '') AS TEXT) AS "pl2_year_pro",
    r."pl2_weight" AS "pl2_weight(r)",
    t."pl2_weight" AS "pl2_weight(t)",
    r."pl2_weight"<>CAST(coalesce(t."pl2_weight", '') AS TEXT) AS "pl2_weight",
    r."pl2_height" AS "pl2_height(r)",
    t."pl2_height" AS "pl2_height(t)",
    r."pl2_height"<>CAST(coalesce(t."pl2_height", '') AS TEXT) AS "pl2_height",
    r."pl2_hand" AS "pl2_hand(r)",
    t."pl2_hand" AS "pl2_hand(t)",
    r."pl2_hand"<>coalesce(t."pl2_hand", '') AS "pl2_hand",
    1
FROM report r
JOIN my_report t ON t.id = r.id
) t2) t3 order by bad desc;
